apiVersion: v1
kind: Pod
metadata:
  name: mysanta
spec:
  containers:
  - name: mysanta-pod
    image: nginx:1.15
    ports:
    - containerPort: 80
    volumeMounts:
    - name: myindex
      mountPath: "/usr/share/nginx/html"
      readOnly: true
  volumes:
  - name: myindex
    configMap:
      name: myindex