---
# kubectl run web --image=nginx --port=80
kind: Pod
apiVersion: apps/v1
metadata:
  name: web
spec:
  containers:
    - name: nginx
      image: nginx
      ports: 
        - containerPort: 80
          protocol: TCP
